name: Release

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Release version'
        required: true
      branch:
        description: 'Branch'
        default: 'main'
        required: true
      tasks:
        description: 'Tasks'
        default: 'build aggregateTestReports publish'
        required: false
  
jobs:
  release:
    name: Release
    uses: redis-field-engineering/redis-github-workflows/.github/workflows/release.yml@main
    with:
      branch: ${{ github.event.inputs.branch }}
      version: ${{ github.event.inputs.version }}
      tasks: ${{ github.event.inputs.tasks }}
    secrets:
      github-user: ${{ secrets.GIT_USER }}
      github-token: ${{ secrets.GIT_ACCESS_TOKEN }}
      gpg-passphrase: ${{ secrets.GPG_PASSPHRASE }}
      gpg-public-key: ${{ secrets.GPG_PUBLIC_KEY }}
      gpg-secret-key: ${{ secrets.GPG_SECRET_KEY }}
      docker-username: ${{ secrets.DOCKER_USERNAME }}
      docker-password: ${{ secrets.DOCKER_PASSWORD }}
      sonatype-username: ${{ secrets.SONATYPE_USERNAME }}
      sonatype-password: ${{ secrets.SONATYPE_PASSWORD }}
      slack-webhook: ${{ secrets.SLACK_WEBHOOK }}